declare module 'lucide-react' {
  import * as React from 'react';
  export type IconComponent = React.FC<any>;

  export const Users: IconComponent;
  export const FolderKanban: IconComponent;
  export const KeyRound: IconComponent;
  export const Copy: IconComponent;
  export const Check: IconComponent;
  export const Plus: IconComponent;
  export const RefreshCw: IconComponent;
  export const Shield: IconComponent;
  export const ShieldCheck: IconComponent;
  export const UserMinus: IconComponent;
  export const UserPlus: IconComponent;
  export const Sparkles: IconComponent;
  export const Info: IconComponent;
  export const FolderPlus: IconComponent;
  export const FileText: IconComponent;
  export const Search: IconComponent;
  export const Crown: IconComponent;
  export const Building2: IconComponent;
  export const LayoutTemplate: IconComponent;
  export const LogIn: IconComponent;
  export const LogOut: IconComponent;
  export const Home: IconComponent;
  export const Menu: IconComponent;
  export const ChevronDown: IconComponent;
  export const ChevronUp: IconComponent;
  export const Lock: IconComponent;
  export const Globe: IconComponent;
  export const X: IconComponent;
  export const User: IconComponent;
  export const Mail: IconComponent;
  export const CheckCircle2: IconComponent;
  export const Save: IconComponent;
  export const RotateCw: IconComponent;
  export const AlertTriangle: IconComponent;
  export const Clock: IconComponent;
  export const FilePlus: IconComponent;
  export const Layers: IconComponent;
  export const ShieldAlert: IconComponent;
  export const Trash2: IconComponent;
  export const Edit: IconComponent;
  export const Edit3: IconComponent;
  export const Eye: IconComponent;
  export const Download: IconComponent;
  export const Bold: IconComponent;
  export const Italic: IconComponent;
  export const List: IconComponent;
  export const ListOrdered: IconComponent;
  export const Code: IconComponent;
  export const Heading: IconComponent;
  export const Heading2: IconComponent;
  export const Heading3: IconComponent;
  export const Link: IconComponent;
  export const Quote: IconComponent;
  export const CheckSquare: IconComponent;
  export const ArrowLeft: IconComponent;
  export const ArrowRight: IconComponent;
  export const ArrowUp: IconComponent;
  export const ArrowDown: IconComponent;
  export const Calendar: IconComponent;
  export const Tag: IconComponent;
  export const FileEdit: IconComponent;
  export const GripVertical: IconComponent;
  export const Indent: IconComponent;
  export const Outdent: IconComponent;
  export const ListPlus: IconComponent;
  export const Columns: IconComponent;
  export const Circle: IconComponent;
  export const HelpCircle: IconComponent;
  export const AlertCircle: IconComponent;
  export const PlusCircle: IconComponent;
  export const Filter: IconComponent;
  export const Printer: IconComponent;
  export const ListTodo: IconComponent;
  export const Table: IconComponent;
  export const FileCode: IconComponent;
  export const RotateCcw: IconComponent;
  export const ListTree: IconComponent;
}

declare module 'marked' {
  export const marked: {
    (src: string, options?: any): string;
    parse(src: string, options?: any): string;
    [key: string]: any;
  };
}
